version: "3.5"
services:
  webserver:
    image: fuerzastudio/nginx-php-fpm:version-.1.0.2
    container_name: server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./php/php.ini:/etc/php/7.4/fpm/php.ini
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./config:/etc/nginx/common
      - ./nginx/htpasswd:/etc/nginx/htpasswd
      - /var/www:/var/www
    networks: 
      dev:
        ipv4_address: 171.28.5.10
  mariadb:
    image: mariadb:10.4.12
    container_name: databases
    restart: always
    volumes:
      - ./databases/data-mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=wordpress_usr
      - MYSQL_PASSWORD=wordpress_password
    ports:
      - '3306:3306'
    depends_on:
      - webserver
    networks: 
      dev:
        ipv4_address: 171.28.5.11
  redis:
    image: redis:6.0.9-alpine
    container_name: redis
    restart: always
    volumes:
      - ./databases/redis:/data
    ports:
      - '6379:6379'
    depends_on:
      - webserver
    networks: 
      dev:
        ipv4_address: 171.28.5.12
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    container_name: phpmyadmin
    environment:
      - PMA_HOSTS=171.28.5.11
      - UPLOAD_LIMIT=20480000K
    restart: always
    links:
      - mariadb
    depends_on:
      - mariadb
    volumes:
      - /sessions
    ports:
      - '8080:80'
    networks: 
      dev:
        ipv4_address: 171.28.5.20

networks: 
  dev:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 171.28.0.0/16